language: go

go:
  - 1.3
  - tip

install:
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/garyburd/redigo/redis
  - go get github.com/ugorji/go/codec
  - go get github.com/satori/go.uuid

notifications:
  email: false
  irc: 
      channels:
          - "chat.freenode.net#wab.io"
      template:
          - "[%{result}] %{repository} (%{author}) (%{commit}) : %{message} "
          - "Build duration: %{duration}"
          - "Build details: %{build_url}"
